import type { Metadata } from "next";
import "./globals.css";
import BackgroundImageContainer from "./components/InteractiveLayout";

export const metadata: Metadata = {
  title: "Makima Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BackgroundImageContainer>{children}</BackgroundImageContainer>
      </body>
    </html>
  );
}
